"""add_low_activity_streak_to_token

Revision ID: 662c3fcbe1c9
Revises: 1abd288fd0a8
Create Date: 2025-09-16 20:55:55.696758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '662c3fcbe1c9'
down_revision: Union[str, None] = '1abd288fd0a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('low_activity_streak', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'low_activity_streak')
    # ### end Alembic commands ###
